# Generated by Django 6.0.2 on 2026-02-17 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_kpifile_delete_kpirating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpifile',
            options={'ordering': ['year', 'quarter']},
        ),
        migrations.AddField(
            model_name='kpifile',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1 (Jan - Mar)'), ('Q2', 'Q2 (Apr - Jun)'), ('Q3', 'Q3 (Jul - Sep)'), ('Q4', 'Q4 (Oct - Dec)')], default='Q1', max_length=2),
        ),
        migrations.AddField(
            model_name='kpifile',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterUniqueTogether(
            name='kpifile',
            unique_together={('employee', 'quarter', 'year')},
        ),
    ]
