# Generated by Django 6.0.2 on 2026-02-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_kpifile_options_kpifile_quarter_kpifile_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hierarchy_order',
            field=models.IntegerField(default=100),
        ),
    ]
