# Generated by Django 6.0.2 on 2026-02-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='brand_accent',
            field=models.CharField(default='#8CB7C4', max_length=7),
        ),
        migrations.AddField(
            model_name='department',
            name='brand_hover',
            field=models.CharField(default='#043d5c', max_length=7),
        ),
        migrations.AddField(
            model_name='department',
            name='brand_primary',
            field=models.CharField(default='#054B70', max_length=7),
        ),
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, upload_to='dept_logos/'),
        ),
    ]
